version: "1"

name: life-helper

services:
  lifehelper-worker:
    image: arisuokay/lifehelper-worker-service:latest
    container_name: lifehelper-worker
    restart: unless-stopped
    env_file:
      - ./env/lifehelper.env
  
  seqlog:
    image: datalust/seq:latest
    container_name: seqlog
    restart: unless-stopped
    ports:
      - "5341:80"
    volumes:
      - ./seqlog:/data
    env_file:
      - ./env/seq.env
