version: "1"

name: life-helper

services:
  lifehelper-worker:
    image: arisuokay/lifehelper-worker-service:latest
    container_name: lifehelper-worker
    restart: unless-stopped
    env_file:
      - ./env/lifehelper.env
      